/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bms_delta_system_wrapper;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
    }
}
